[log]
  level = "ERROR"

[accessLog]
  format = "json"
  bufferingSize = 0

[api]
  dashboard = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"
  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.http.tls]
  [entryPoints.traefik]
    address = ":8080"
    [entryPoints.traefik.http.tls]

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = false
    watch = true

[certificatesResolvers.letsencrypt.acme]
  storage = "/etc/traefik/acme/acme.json"
